### ISSUE TITLE
Add pjsip support?

### ISSUE THREAD

**Issue by SergeyDjam** [heltonmarx/goami#10]
Hello, whether support of pjsip is planned?

**Comment by heltonmarx** [comment]
The project was originally designed to be an `Go` interface to Asterisk Manager Interface through the [tcp API](https://wiki.asterisk.org/wiki/display/AST/The+Asterisk+Manager+TCP+IP+API).
In the case of [pjsip](http://www.pjsip.org/), it's necessary create a _wrapper_ in `Go` using [cgo](https://golang.org/cmd/cgo/), being implemented in another project with other name.
What do you have in mind regarding this ?

**Comment by SergeyDjam** [comment]
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+AMI+Actions 

goami doesn't support Asterisk 13 and is newer?

**Comment by heltonmarx** [comment]
PJSIP actions added on ami.v13 branch and master
