### ISSUE TITLE
Socket run get stack on read error

### ISSUE THREAD

**Issue by lmendes86** [heltonmarx/goami#16]
When you receive an `EOF` in the `reader.ReadString('\n')` in run go routing in a Socket the `s.Close()` is executed but after executing `close(s.shutdown)` the is waiting for itself to end, that is never. This generates the go routing to get stack, generating, between other things, the TCP connection to get stack in `CLOSE_WAIT` status.
The issue is simple to reproduce when you are allow to connect to the AMI but you have a wrong password for the given user.
I don't know why you add the waiting group here but I made tests without it and everything went alright.

**Comment by heltonmarx** [comment]
I created this PR : https://github.com/heltonmarx/goami/pull/17 , please take look this will fix the issue.
