### ISSUE TITLE
Connection reset 

### ISSUE THREAD

**Issue by samuel1992** [heltonmarx/goami#3]
Hello Helton. Sorry to open an issue, I really know its not a problem in the goami library, but I need your help, if you could, of course.
Im doing this code : 
```
for {
    queuesummary, err := ami.QueueSummary(socket, uuid, "default")
    if err != nil {
        log.Fatal("QueueSummary() ",err)
        return
    }
    log.Println(queuesummary)
}

```
So In a very short time of this loop, I got my connection reseted by asterisk ami, but I didn't see nothing at asterisk logs.
The "err" is : `2017/04/19 02:35:57 QueueSummary() write tcp 000.000.000.000:48034->111.111.111.111:8426: write: connection reset by peer`
exit status 1

Do you know something I could do to otimize my code avoiding this kind of situation? 

Thank you.

**Comment by samuel1992** [comment]
Hello @heltonmarx. Thank you for answer me!
I did it as you recommended and it worked fine!
But, now I have another problem. I have one agent logged in queue "default", then I run this code to see the "Available" parameter of QueueSummary event, I let it run in loop (with a ticker on 100ms), so I make a call from the agent extension and the information show to me at least 4 seconds delayed.
For exeample:
**my code** 
   ```
 trigger := time.NewTicker(time.Millisecond * 100).C
    for {
      select {
        case <-trigger:
          qs, err := ami.QueueSummary(socket, uuid, "default")
          if err != nil {
            log.Fatal("QueueSummary() error:",err,"Count",count)
          }

          if len(qs["Event"]) > 0 && qs["Event"][0] == "QueueSummary"{
            log.Println(qs["Available"])
          }
        }
    }
```
**The output**
```
2017/04/19 11:56:13 [1]
2017/04/19 11:56:13 [1]
2017/04/19 11:56:14 [1]
2017/04/19 11:56:14 [1]
2017/04/19 11:56:14 [1]
2017/04/19 11:56:14 [1]
2017/04/19 11:56:15 [1]
2017/04/19 11:56:15 [1]
2017/04/19 11:56:15 [1]
2017/04/19 11:56:16 [1]
2017/04/19 11:56:16 [1]
2017/04/19 11:56:16 [1]
2017/04/19 11:56:17 [1]
2017/04/19 11:56:17 [1]
2017/04/19 11:56:17 [1]
2017/04/19 11:56:17 [1]
2017/04/19 11:56:18 [1]
2017/04/19 11:56:18 [1]
2017/04/19 11:56:18 [1]
2017/04/19 11:56:19 [1]
2017/04/19 11:56:19 [1]
2017/04/19 11:56:19 [1]
2017/04/19 11:56:21 [0]
2017/04/19 11:56:21 [0]
2017/04/19 11:56:22 [0]
```

The problem here is: my queue "default" had 0 Available member at 2017/04/19 11:56:13  but it just show me the information at 2017/04/19 11:56:21 [0], few seconds delayed.
I was following the same event by telnet connection and it was right there, so my asterisk is sending the events at the right time. I have no clue what it means. =/

**Comment by samuel1992** [comment]
Sorry @heltonmarx . I didn't have update by the new branch 'fix-queue-summary'. 
I clone the branch 'fix-queue-summary' and it work fine, without delay =).

**Comment by heltonmarx** [comment]
Nice !
Can I close the issue and merge the branch ?

**Comment by samuel1992** [comment]
@heltonmarx sure! It is all ok, thank you!
