### ISSUE TITLE
confbridge actions/events

### ISSUE THREAD

**Issue by beqabeqa473** [heltonmarx/goami#5]
hi.

please add confbridge actions/events to this package.

**Comment by heltonmarx** [comment]
I created this [pull request](https://github.com/heltonmarx/goami/pull/6), please check if it is useful for you, or I missing something.

**Comment by beqabeqa473** [comment]
hi.

looks good.

thank you.

**Comment by heltonmarx** [comment]
Implemented on commit 095a4ba10850405be1cfa1d579963614f2931107
