### ISSUE TITLE
Unable to shutdown on Close(): infinite loop

### ISSUE THREAD

**Issue by vagoff** [heltonmarx/goami#7]
socket.Recv() does not ends after shutdown socket closed leading to infinite loop in read()

patch to solve:

```
diff -uwrd old/socket.go new/socket.go
--- old/socket.go	2017-10-11 15:06:17.553303464 +0300
+++ new/socket.go	2017-10-11 15:08:10.601014898 +0300
@@ -7,8 +7,11 @@
 	"net"
 	"strings"
 	"sync"
+	"errors"
 )
 
+var ErrClosed = errors.New("socket closed") 
+
 // Socket holds the socket client connection data.
 type Socket struct {
 	conn     net.Conn
@@ -70,7 +73,7 @@
 				return buffer.String(), nil
 			}
 		case <-s.shutdown:
-			return buffer.String(), nil
+			return buffer.String(), ErrClosed
 		}
 	}
 }
```

**Comment by vagoff** [comment]
By the way, thanks for the lib! As far as I can see it has chances to be best amongst competitors.

**Comment by heltonmarx** [comment]
First of all, 
Thank you ! For me it's a pleasure this library is helpful for someone. 
Well, instead creating `ErrClosed`, I would like add as return `io.EOF`. 
Maybe it sounds more reasonable though.

**Comment by vagoff** [comment]
Thanks for reacting so fast! Very good. I think you're right about io.Err, but I'm working with Go for less than one week so I have not much experience yet, honestly =)
